services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - proxy

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - backend-db
    
  # Backend users micro
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp-data:/var/www/html
    networks:
      - backend-db
      - proxy
    depends_on:
      - mariadb

# Networks configuration
networks:
  backend-db:
    driver: bridge
  proxy:
    driver: bridge

# Volumes
volumes:
  wp-data: