services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - ./requirements/nginx/.env
    ports:
      - "443:443"
    networks:
      - proxy
    depends_on:
      - mariadb
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  wordpress:
    container_name: wordpress
    env_file:
      - .env
      - ./requirements/wordpress/.env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp-data:/var/www/html
    networks:
      - backend-db
      - proxy
    depends_on:
      - mariadb
      - redis
    restart: always

  ### BONUS ###

  redis:
    container_name: redis
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    volumes:
      - wp-data:/var/www/html
    networks:
      - backend-db
    restart: always

  ftp:
    container_name: ftp
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile
    env_file:
      - ./requirements/ftp/.env
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wp-data:/home/ftpusers/ftpuser
    networks:
      - proxy
    restart: always

  gatsby-app:
    container_name: gatsby-app
    build: 
      context: ./requirements/gatsby-app
      dockerfile: Dockerfile
    networks:
      - proxy
    restart: always

  alien-eggs:
    container_name: alien-eggs
    build:
      context: ./requirements/alien-eggs
      dockerfile: Dockerfile
    networks:
      - proxy
    restart: always

# Networks configuration
networks:
  backend-db:
    driver: bridge
  proxy:
    driver: bridge

# Volumes
volumes:
  wp-data:
    driver: local
    driver_opts:
      type: none
      device: /home/crea/data/
      o: bind

  db-data:
    driver: local
    driver_opts:
      type: none
      device: /home/crea/data/
      o: bind
