services:

  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - proxy
    depends_on:
      - wordpress
      - mariadb

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - db-data:/var/lib/mariadb
    networks:
      - backend-db
    
  # Backend users micro
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp-data:/wordpress/var #adjust wp volume path
    networks:
      - backend-db
      - proxy
    depends_on:
      - mariadb

# Networks configuration
networks:
  backend-db:
    driver: bridge
  proxy:
    driver: bridge

# Volumes
volumes:
  db-data:
  wp-data