global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/certs/prometheus.crt
      key_file: /etc/prometheus/certs/prometheus.key
      insecure_skip_verify: true
    basic_auth:
      username: admin
      password: ${PROMETHEUS_PASSWORD}
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alien-eggs'
    metrics_path: '/metrics'
    scheme: http
    static_configs:
      - targets: ['alien-eggs:8000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(http_requests_total|active_http_requests)'
        action: keep