global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds
  evaluation_interval: 15s  # Evaluate alerts every 15 seconds

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"  # Scrape Prometheus' own metrics

  - job_name: "alien-eggs"
    static_configs:
      - targets:
          - "alien-eggs:8060"  # Scrape metrics from the alien-eggs service
