# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: admin
      password: ${PROMETHEUS_PASSWORD}
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'wordpress'
    static_configs:
      - targets: ['wordpress:9000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:443']
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'alien-eggs'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['alien-eggs:8000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(http_requests_total|active_http_requests)'
        action: keep